Ehpr 5 mass email send
bcgov/ehpr2 pull request #9
Opened 2021-11-25 22:51 UTC by dbayly-freshworks

This is still very much a WIP . I welcome your feedback! 

Current features include: 
* Authentication and sending emails with Ches 
* generating mock csv with 10k rows and uuids 
* asynchronous sending 
* rate limiting
* Automatic refresh and retry when a token expires
* Store failed results in a csv 
* Mocked out random delay in sending

2021-11-26 16:30 UTC, fwpushan requested changes
My suggestions  are
1. Put scripts as different package. Api is a node application with an entry-point. Also each scripts are standalone node applications.
2.  If there is any reusable functionality, put it either in common package or separate package.

2021-11-26 17:04 UTC, fwpushan commented on .gitignore
> +**/*.env
Put all env variables in root. Because env will be injected from root of the repo.

2021-11-26 17:50 UTC, arranfw reviewed
Curious about the decision to write this in JS

The script in HCAP had retry functionality for network disruptions or other intermittent failures, could we add that here? It could possibly reduce failed sends. Or do we just intend to re-run the script on the list of failed sends afterwards?

2021-11-26 17:50 UTC, arranfw commented on packages/api/src/scripts/emailSend.js
> +async function updateToken() {
Could this be renamed to `getChesToken` or something to be more accurate for what it does?

2021-11-26 17:50 UTC, arranfw commented on packages/api/src/scripts/generatecsv.js
> +const faker = require('faker');
We need to install these packges somewhere right?

2021-12-03 13:24 UTC, fwpushan requested changes
As per new project structure. This is not reusable component. Please put it into apps.

Otherwise LGTM.

```suggestion
This is standalone local script. We can get input as cmd argument (instead of ENV) for that we can use this https://www.npmjs.com/package/minimist
```

2021-12-10 19:09 UTC, dbayly-freshworks commented
Closing this as it needs a rework. Will reopen when it is ready.

2021-12-10 19:09 UTC, closed without merging